### ISSUE TITLE
Storage API for Titanium

### ISSUE THREAD

**Issue by boardmain** [realtime-framework/Storage#1]
Hi, is also available the API for Titanium SDK?

**Comment by realtime-framework** [comment]
Unfortunately not yet.

But since Storage exposes a JSON REST API you can use the Ti.Network module to store and retrieve data from your tables.
More at http://developer.appcelerator.com/question/145460/retrieve-json-from-server-and-commonjs-module

The Storage REST API documentation can be found at http://storage-public.realtime.co/documentation/rest/1.0.0/realtime.storage.operations.html
